# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '372b9d51-de1e-4d74-841c-6af19b523032'
  imageRepository: 'wiseflux'
  containerRegistry: 'wiseflux.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'wiseflux2c7c-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: SetNamespace
  displayName: Set Namespace Variable
  jobs:
  - job: SetNamespace
    displayName: Determine Namespace
    pool:
      vmImage: $(vmImageName)
    steps:
    - powershell: |
        if ($env:BUILD_SOURCEBRANCHNAME -eq "master") {
          echo "##vso[task.setvariable variable=namespace;isOutput=true]master"
        } else {
          echo "##vso[task.setvariable variable=namespace;isOutput=true]dev"
        }
      env:
        BUILD_SOURCEBRANCHNAME: $(Build.SourceBranchName)
      name: setvarStep

- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: 
  - Build
  - SetNamespace
  variables:
    namespace: $[ dependencies.SetNamespace.outputs['SetNamespace.setvarStep.namespace'] ]
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'guiturterawiseflux.wiseflux'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              namespace: $(namespace)  # Now this will work

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
              namespace: $(namespace)
