# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '372b9d51-de1e-4d74-841c-6af19b523032'
  imageRepository: 'wiseflux'
  containerRegistry: 'wiseflux.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'wiseflux2c7c-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: SetNamespace
  displayName: Set Namespace Variable
  jobs:
  - job: SetNamespace
    displayName: Determine Namespace
    pool:
      vmImage: $(vmImageName)
    steps:
    - powershell: |
        if ($env:BUILD_SOURCEBRANCHNAME -eq "master") {
          echo "##vso[task.setvariable variable=namespace;isOutput=true]master"
        } else {
          echo "##vso[task.setvariable variable=namespace;isOutput=true]dev"
        }
      env:
        BUILD_SOURCEBRANCHNAME: $(Build.SourceBranchName)
      name: setvarStep

- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: 
  - Build
  jobs:
  - deployment: Deploy
    displayName: Deploy to Azure Web App for Containers
    pool:
      vmImage: $(vmImageName)
    environment: 'Prod.master'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Azure Web App for Containers'
            inputs:
              azureSubscription: '38c5c508-1dee-43c3-bceb-43a462cbfb4d'
              appName: 'wiseflux-backend-prod'
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)